/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Virtual Key
 #	author : miyako
 #	2015/06/08
 #
 # --------------------------------------------------------------------------------*/



// --- Virtual Key
void POST_VIRTUAL_KEY(sLONG_PTR *pResult, PackagePtr pParams);
void Test_virtual_key(sLONG_PTR *pResult, PackagePtr pParams);
